export const cityList: string[] = [
  "Abohar",
  "Adampur",
  "Ahmedgarh",
  "Akalgarh",
  "Alawalpur",
  "Amloh",
  "Amritsar",
  "Anandpur Sahib",
  "Ajnala",
  "Arniwala Sheikh Subhan",
  "Badhni Kalan",
  "Bagha Purana",
  "Bakapur",
  "Banga",
  "Banur",
  "Bareta",
  "Barnala",
  "Bassi Pathana",
  "Batala",
  "Bathinda",
  "Begowal",
  "Behrampur",
  "Bhagta Bhai Ka",
  "Bharowal",
  "Bhikhi",
  "Bhikhiwind",
  "Bhisiana",
  "Bhogpur",
  "Bhucho Mandi",
  "Bhunga",
  "Budhlada",
  "Chohal",
  "Chak Saida",
  "Chamkaur Sahib",
  "Cheema",
  "Chheharta",
  "Dasuya",
  "Dera Baba Nanak",
  "Dera Bassi",
  "Dharamkot",
  "Dhariwal",
  "Dhilwan",
  "Dhuri",
  "Dirba",
  "Doda",
  "Doraha",
  "Faridkot",
  "Fatehgarh Churian",
  "Fatehgarh Sahib",
  "Fatehabad",
  "Fazilka",
  "Firozpur",
  "Firozpur Cantt",
  "Gardhiwala",
  "Garhshankar",
  "Ghagga",
  "Ghanaur",
  "Gidderbaha",
  "Goraya",
  "Govindgarh",
  "Gurdaspur",
  "Guru Har Sahai",
  "Hariana",
  "Harike",
  "Hoshiarpur",
  "Hussainpur",
  "Ibban",
  "Jagraon",
  "Jaito",
  "Jalandhar",
  "Jalandhar Cantt",
  "Jallalabad",
  "Jandiala Guru",
  "Jugial",
  "Kahnuwan",
  "Kalanaur",
  "Kapurthala",
  "Kartarpur",
  "Karoran",
  "Katani Kalan",
  "Khadur Sahib",
  "Khadoor Sahib",
  "Khagaul",
  "Khanna",
  "Kharar",
  "Khemkaran",
  "Khilchian",
  "Kiranwali",
  "Kot Fatta",
  "Kot Ise Khan",
  "Kotkapura",
  "Kurali",
  "Lalru",
  "Lehragaga",
  "Lohian Khas",
  "Longowal",
  "Ludhiana",
  "Machhiwara",
  "Majitha",
  "Makhu",
  "Malerkotla",
  "Malout",
  "Mandi Gobindgarh",
  "Mansa",
  "Maur",
  "Mehatpur",
  "Miani",
  "Moga",
  "Mohali (SAS Nagar)",
  "Moonak",
  "Morinda",
  "Mukerian",
  "Muktsar",
  "Mullanpur Dakha",
  "Mullanpur Garibdas",
  "Nabha",
  "Nakodar",
  "Nangal",
  "Nawanshahr",
  "Naya Gaon",
  "Nurmahal",
  "Pathankot",
  "Patiala",
  "Patti",
  "Payal",
  "Phagwara",
  "Phillaur",
  "Qadian",
  "Raikot",
  "Raja Sansi",
  "Rajpura",
  "Ramdas",
  "Rampura Phul",
  "Rayya",
  "Rupnagar",
  "Sahnewal",
  "Samana",
  "Samrala",
  "Sanaur",
  "Sangrur",
  "Sansarpur",
  "Sardulgarh",
  "Shahkot",
  "Sham Churasi",
  "Shekhpura",
  "Sirhind",
  "Sri Hargobindpur",
  "Sultanpur Lodhi",
  "Sunam",
  "Talwandi Bhai",
  "Talwara",
  "Tappa Mandi",
  "Tarn Taran",
  "Tibba",
  "Tohana",
  "Urmar Tanda",
  "Zira",
  "Zirakpur",

  // --- Additional Census Towns ---
  "Ajnoha",
  "Allowal",
  "Badowal",
  "Bhabat",
  "Bohra",
  "Chachoki",
  "Gehrwin",
  "Gobindpur",
  "Harion Kalan",
  "Jandi",
  "Kalewal",
  "Khambra",
  "Khothran",
  "Lalpur",
  "Madhopur",
  "Majri",
  "Mandiani",
  "Mehlanwali",
  "Mughal Majra",
  "Naraingarh",
  "Nathana",
  "Nasrali",
  "Parmandal",
  "Pawti",
  "Pipli",
  "Rurewal",
  "Sandharsi",
  "Sohal",
  "Ucha Pind"
];